-- AlterTable
ALTER TABLE `home` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `provider` MODIFY `RegisteredAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` MODIFY `RegisteredAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
